# Generated by Django 2.1.7 on 2019-02-24 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.CharField(choices=[('Left', (('VL1', 'Eye/high area, left.'), ('VL2', 'Nose,/medium area, left.'), ('VL3', 'Mandibular, left.'))), ('Right', (('VR1', 'Eye/high area, right.'), ('VR2', 'Nose,/medium area, right.'), ('VR3', 'Mandibular, right.'))), ('---', '---')], max_length=3)),
                ('note', models.CharField(default='', max_length=1000)),
                ('rank', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('meds', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
