# Generated by Django 2.1.7 on 2019-02-25 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pains', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
